# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='skills.Skill'),
            preserve_default=False,
        ),
    ]
