# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210305_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Company',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
