# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20210304_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
